// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_MyWidgetCollectionPlugin.cpp"
#include "EWIEGA46WW/moc_slidertext.cpp"
#include "EWIEGA46WW/moc_slidertextplugin.cpp"
